spring:
  application:
    name: tumblerin
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}   # 환경변수에서 API 키 읽기
      embedding:
        model: text-embedding-3-small  # 추후 성능 개선 필요시 large로 개선
  datasource:
    url: ${DB_JDBC_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver #PostgreSQL DRIVER로 수정
  jpa:
    show-sql: false
    database: postgresql #PostgreSQL
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: false
        use_sql_comments: false
      dialect: org.hibernate.dialect.PostgreSQLDialect #PostgreSQL
    open-in-view: false

server:
  port: ${PORT:8080}

jwt:
  secret: ${JWT_SECRET}
