spring:
  datasource:
    url: ${DB_JDBC_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    database: mysql
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        dialect: org.hibernate.spatial.dialect.mysql.MySQL8SpatialDialect
    open-in-view: false

server:
  port: ${PORT:8080}

jwt:
  secret: ${JWT_SECRET}

ai:
  openai:
    api-key: ${OPENAI_API_KEY}
    embedding:
      model: text-embedding-3-small