name: CI/CD Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Java 설치 (빌드용)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17  

      # 4. Gradlew 실행 권한 부여
      - name: Make Gradlew executable
        run: chmod +x ./gradlew

      # 5. JAR 빌드
      - name: Build JAR
        run: ./gradlew clean build -x test

      # 6. JAR을 EC2로 복사
      - name: Copy JAR to EC2
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: build/libs/tumblerin-0.0.1-SNAPSHOT.jar
          target: /home/ubuntu/project/Tumbloom-BE/build/libs/

      # 7. EC2에서 배포 스크립트 실행
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Nginx 중지
            sudo systemctl stop nginx

            # 기존 tumblerin 프로세스 종료
            pkill -f tumblerin-0.0.1-SNAPSHOT.jar || true

            mkdir -p /home/ubuntu/project/Tumbloom-BE/logs

            # 새 JAR 실행 (백그라운드, nohup)
            cd /home/ubuntu/project/Tumbloom-BE/build/libs
            nohup java -jar tumblerin-0.0.1-SNAPSHOT.jar > ../logs/tumblerin.log 2>&1 &
            
            # Nginx 재시작
            sudo systemctl restart nginx
            sudo systemctl status nginx
